### ISSUE TITLE
Roles not given on join

### ISSUE THREAD

**Issue by Itz-Cook1e** [Alfie-Phillips/Mark#9]
When leaving and rejoining the Discord server, any level role you have are not given to you again. However, all your levels stay the same. So you can be level 10 but not have the 10-19 role.

**Comment by alfiephillips** [comment]
@Itz-Cook1e Thanks for informing me on this. Do you have any suggestions on a quick fix by any chance? Haven't been programming lately have been having exams lol 😂

**Comment by Itz-Cook1e** [comment]
I know an inefficient way but it works.

On join just check level. Then if user has a level give them said role.

**Comment by alfiephillips** [comment]
@Itz-Cook1e If your feeling like it you can contribute with this if you want. It's ok if you don't want too though I understand.

**Comment by Itz-Cook1e** [comment]
I can probably see what I can do. If I can't do it I'll let you know though.

**Comment by Itz-Cook1e** [comment]
> I can probably see what I can do. If I can't do it I'll let you know though.

It you haven't noticed, I haven't even started looking for a solution. 

I don't think it's necessary anymore as the server is extremely dead.

**Comment by alfiephillips** [comment]
Really?
